### ISSUE TITLE
Port is already in use

### ISSUE THREAD

**Issue by Ernie6711** [astaxie/beego#1404]
I created a simple test web app with ```bee new test ``` and was trying to enable TLS. However the error message confused me a lot. Could you please help?

Mac OS X: El Capitan, firewall off

> bee version
bee   :1.3.0
beego :1.5.0
Go    :go version go1.5.1 darwin/amd64

> bee run
2015/10/26 04:24:28 [INFO] Initializing watcher...
2015/10/26 04:24:28 [TRAC] Directory(/Users/xxx/gocode/src/testBeeGo/test/controllers)
2015/10/26 04:24:28 [TRAC] Directory(/Users/xxx/gocode/src/testBeeGo/test)
2015/10/26 04:24:28 [TRAC] Directory(/Users/xxx/gocode/src/testBeeGo/test/routers)
2015/10/26 04:24:28 [TRAC] Directory(/Users/xxx/gocode/src/testBeeGo/test/tests)
2015/10/26 04:24:28 [INFO] Start building...
2015/10/26 04:24:30 [SUCC] Build was successful
2015/10/26 04:24:30 [INFO] Restarting test ...
2015/10/26 04:24:30 [INFO] ./test is running...
2015/10/26 04:24:30 [asm_amd64.s:1696] [I] http server Running on :8080
2015/10/26 04:24:30 [asm_amd64.s:1696] [I] https server Running on :10443
2015/10/26 04:24:30 [asm_amd64.s:1696] [C] ```ListenAndServeTLS: %!(EXTRA *net.OpError=listen tcp :10443: bind: address already in use)```

> lsof -i tcp:10443
(nothing)
> lsof -i tcp:8080
(nothing)

Below are my configuration:
app.conf:
```
appname = test
httpport = 8080
runmode = dev
```
main.go
```
package main

import (
	"github.com/astaxie/beego"
	_ "testBeeGo/test/routers"
)

func main() {
	beego.EnableHttpTLS = true
	beego.HttpCertFile = "ssl_cert/server.crt"
	beego.HttpKeyFile = "ssl_cert/server.key"
	beego.Run()
}
```

**Comment by xtea** [comment]
check your port `8080` if in use

**Comment by Ernie6711** [comment]
After recompiling my Beego libraries this problem is resolved.

**Comment by ZloiBubr** [comment]
Still exists at beego 1.6.
When using HTTPS - port is ok for first run, next run it always busy. no matter what you doing. Changing port mostly allows to run, but sometimes give port busy error from first attempt. 
Return port back after start on other port allows to run on original port.
Env: Mac OS, Webstorm.

**Comment by Ernie6711** [comment]
Echoing ZloiBubr, this still happpens on Mac OS with the same config., but never on Amazon Linux(free, micro).

**Comment by nightrune** [comment]
Yeah I have the same thing happening on FreeBSD now as well. Just occasionally it'll just fail to bind to the socket. netstat before and after show no in use sockets with the same port.

**Comment by nightrune** [comment]
@ZloiBubr I seem to have found the issue.

https://github.com/astaxie/beego/blob/master/app.go#L144

There is a race condition with app.Server.Addr,
On line 146 app.Server.Addr is set and the same value is used on line 161. I think its possible the sockets race to connect to the tls port.
Essentially,
app.Server.Addr is set, then the http sock starts with the incorrect addr string. Then the TLS socket attempts to start on the same port.

The quick fix is to increase the time on line 144 this issue seems to go away.  I set this for a millisecond, but that does not guarantee it will fix the issue. It seems the graceful server has the same issue as well...
