### ISSUE TITLE
Does Beego ORM always prepare stmt for every sql execute?

### ISSUE THREAD

**Issue by simpleton** [astaxie/beego#1454]
I found the value of `Com_stmt_prepare` and `Com_stmt_close` increased when I query some data for db by beego orm.

```
Com_stmt_close	29884224
Com_stmt_execute	29884861
Com_stmt_fetch	0
Com_stmt_prepare	29965951
```

Is that for increasing performance ?

**Comment by fuxiaohei** [comment]
the standard package `database/sql` runs prepared statement to every sql queries.

https://golang.org/src/database/sql/sql.go#L932

The details are depends on your database driver implementation.

**Comment by simpleton** [comment]
@fuxiaohei Thanks your feedback.
Why always run prepared for every query? If you always close the stmt when one query finished, it wouldn't help you to improve the performance in my opinion.

**Comment by fuxiaohei** [comment]
@simpleton  I think the reason is the `Exec(sql,args...)` style. It passed arguments to sql string. So It prepares the sql for paramaters in `database/sql` as default. 

In `go-sql-driver/mysql`, it queries directly in code, but I'm not sure.

https://github.com/go-sql-driver/mysql/blob/master/connection.go#L300
https://github.com/go-sql-driver/mysql/blob/master/connection.go#L351
