### ISSUE TITLE
Using filter with splat (*) breaks docs router

### ISSUE THREAD

**Issue by pjoe** [astaxie/beego#1550]
When using a filter added with splat, docs router breaks, e.g.
```go
beego.InsertFilter("*", beego.BeforeStatic, RedirectHTTP)
```
From what I could see the issue is that ctx.Input.Params[":splat"] was set when matching for the filter and never cleared before running the docs router.

As a workaround I added this to my filter:
```go
// make sure :splat gets cleared in order to not confuse /docs
delete(ctx.Input.Params, ":splat")
```

**Comment by pjoe** [comment]
This gets even worse in 1.6 where the workaround won't work as ctx.Input.Params is now an accessor function instead of having direct access to delete the param.

Think I will make a PR with something like ctx.Input.RemoveParam

**Comment by pjoe** [comment]
Tried using:
```go
ctx.Input.SetParam(":splat", "")
```

But turns out SetParam won't overwrite existing params

**Comment by pjoe** [comment]
Added PR to fix SetParam: https://github.com/astaxie/beego/pull/1637

The above workaround now works

**Comment by danielscottt** [comment]
👋 

I'm running into this issue too, where my filter is using the `BeforeExec` state in the pipeline. We could clear params in router's `execFilter`, I think, so they were reset on context as it passes through each router.  Does that sound reasonable or is it bad form to change the state of input params as the context passes through the pipeline?

**Comment by danielscottt** [comment]
Ok -- Disregard that above comment.

After further exploration, I see that this is likely a side effect of using a `BeforeExec` on a route that also uses splat, because it's the router which sets these params, and a filter which is at the `BeforeExec` stage in the pipeline is the last writer!  The router doesn't have a chance to reset params again.

I'm moving my filter to `BeforeRouter` for now.  If I end up needing session state down the road I'll revisit then.

Thanks!
