### ISSUE TITLE
静态文件找不到，状态码返回200而不是404

### ISSUE THREAD

**Issue by shshxy98** [astaxie/beego#1641]
bee :1.4.1
beego :1.6.0
Go :go version go1.5rc1 linux/amd64
![Uploading image.png…]()

**Comment by youngsterxyf** [comment]
@shshxy98 please upload your image，I can not see it

![image](https://cloud.githubusercontent.com/assets/834231/12703069/54e93568-c874-11e5-8909-67e3bc7190b4.png)

**Comment by shshxy98** [comment]
the imga 
![qq 20160201215907](https://cloud.githubusercontent.com/assets/10886204/12719318/406eca74-c92f-11e5-862f-17f1f750d2fb.png)

**Comment by shshxy98** [comment]
static file or not exit router

**Comment by youngsterxyf** [comment]
@astaxie is this a bug or a feature? :smile:

**Comment by youngsterxyf** [comment]
If it is a bug, i will try to fix it

**Comment by youngsterxyf** [comment]
To fix it,  add this line:

![image](https://cloud.githubusercontent.com/assets/834231/12720180/59579d36-c934-11e5-858d-1611b728d00e.png)

**Comment by shshxy98** [comment]
thinks,that  realy works
![image](https://cloud.githubusercontent.com/assets/10886204/12721440/c8f3a47c-c93a-11e5-879e-8b19d7818c9c.png)

**Comment by youngsterxyf** [comment]
@shshxy98 No, not close this issue

**Comment by thanzen** [comment]
@youngsterxyf , is it possible to get the recent fixes merged to master branch as our app is currently stuck at the moment as the images are not showing correctly. I think many of the recent fixes  should be included into master sooner than later since some of them are "critical" fixes to the users.
Again, I really enjoy work with Beego -- simple and powerful. Thanks for you guys great work.

**Comment by youngsterxyf** [comment]
@astaxie
