### ISSUE TITLE
docs router doesn't work with CORS filter set

### ISSUE THREAD

**Issue by hverlin** [astaxie/beego#1684]
Thank you for this great framework!

As I am using my beego backend with an angular JS application, I am forced to change the CORS options. (see the code below)

Unfortunately, this breaks the docs router and can no longer test the backend with swagger.

```go
func main() {

	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
		AllowCredentials: true,
	}))

	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}

	beego.Run()
}
```
However, if I comment the following lines, I can use swagger but I can't use it with  my angular frontend. 

```go
	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
		AllowCredentials: true,
	}))
```

Do you have any ideas on how to fix this ? Thank you!

**Comment by jesusjjf** [comment]
Have you been able to find a solution for this?

**Comment by steamonimo** [comment]
Yupp, same problem. Right now beego can not handle CORS properly.

We have a server for our frontend and a server for our restless api. Because of this difference in origin the CORS handling is needed. The filter you have provided should allow any origin. But in our scenario we just see an access via OPTIONS that leads to a NOMATCH message from the beego router.

Sadly the latest edition of chrome has removed the --disable-web-security flag. Thus we need CORS in beego to work properly for our development process.

**Comment by lenye** [comment]
same problem

**Comment by astaxie** [comment]
Please  update to beego1.7. Now the docs is swagger.json. And no long need the Docs endpoints.
