### ISSUE TITLE
路由设置 namespace 中使用 beego.NSBefore  后 cors 插件失效

### ISSUE THREAD

**Issue by netskyline** [astaxie/beego#1857]
bee api 系统，通过 cors 插件，可以实现 api 的跨域访问。

```
beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"OPTIONS", "HEAD", "GET", "POST", "PUT", "PATCH", "DELETE"},
		AllowHeaders:     []string{"Origin", "Accept", "Content-Type", "Authorization", "X-Requested-With"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
}))
```

但是，同时在 namespace 中使用 beego.NSBefore 后，cors 失效，api 就不能跨域访问了。

```
beego.NSBefore(
        apiauth.AuthenticationFilter(),
),
```

-> % bee version
bee   :1.4.1
beego :1.6.1
Go    :go version go1.5 darwin/amd64
-> % go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxx/projects/go"
GORACE=""
GOROOT="/Users/xxx/opt/go"
GOTOOLDIR="/Users/xxx/opt/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by youngsterxyf** [comment]
@netskyline `beego.NSBefore(apiauth.AuthenticationFilter())` is equivalent to `beego.InsertFilter("*", beego.BeforeRouter, apiauth.AuthenticationFilter())`, so these filters work depending on the order you add them. Instead of using `beego.NSBefore(apiauth.AuthenticationFilter())`, i think it may be better to use `beego.InsertFilter("*", beego.BeforeExec, apiauth.AuthenticationFilter())`, you can try it.
