### ISSUE TITLE
testing bug

### ISSUE THREAD

**Issue by xieyuping** [astaxie/beego#2075]
测试不能加载conf/app.conf
beego.TestBeegoInit(apppath)

==>
// TestBeegoInit is for test package init
func TestBeegoInit(ap string) {
	os.Setenv("BEEGO_RUNMODE", "test")
	appConfigPath = filepath.Join(ap, "conf", "app.conf")
	os.Chdir(ap)
	initBeforeHTTPRun()
	// parseConfig(appConfigPath)
}

原因是beego.go缺少一句  parseConfig(appConfigPath)

另外 bee new projectName 时生成的tests命名规范不对  TestMain ==>Test_Main

**Comment by ysqi** [comment]
hello @xieyuping , 请告知你所使用的Beego版本，bee 生成的项目中，tests文件夹下是有初始化测试初始化代码的 [Code](https://github.com/beego/bee/blob/master/new.go#L200)，其中可以解析app.confg。

而你所说的 TestMain 测试方法命名是符合规范的，见[Testing](https://golang.org/doc/code.html#Testing) ,测试方法命名格式`TestXXX`，在Golang中是不推荐在命名中使用下划线的。

**Comment by astaxie** [comment]
fix in beego 1.7.0

**Comment by airylinus** [comment]
@ysqi  在 golang 1.4 以后的版本中 TestMain() 方法有特殊用途：
详见 release note ： https://golang.org/doc/go1.4

The testing package has a new facility to provide more control over running a set of tests. If the test code contains a function
`func TestMain(m *testing.M) `
that function will be called instead of running the tests directly. The M struct contains methods to access and run the tests.
