### ISSUE TITLE
orm getFlatParams method nil pointer dereference

### ISSUE THREAD

**Issue by it-man-cn** [astaxie/beego#2106]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.5.2
beego 1.7

2. What operating system and processor architecture are you using (`go env`)?
Centos 6.4

3.code
https://github.com/astaxie/beego/blob/master/orm/db_utils.go#L148
```
				if fi != nil && fi.fieldType == TypeDateField {
					arg = v.In(tz).Format(formatDate)
				} else if fi.fieldType == TypeDateTimeField {
					arg = v.In(tz).Format(formatDateTime)
				} else {
					arg = v.In(tz).Format(formatTime)
				}
```
the code L148 should have a nil check before  fi.fieldType == TypeDateTimeField

4.error log
2016/08/22 15:07:23 [router.go:896] [C] the request url is  /auth/v2.0/login
2016/08/22 15:07:23 [router.go:897] [C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2016/08/22 15:07:23 [router.go:903] [C] /usr/local/go/src/runtime/asm_amd64.s:437
2016/08/22 15:07:23 [router.go:903] [C] /usr/local/go/src/runtime/panic.go:423
2016/08/22 15:07:23 [router.go:903] [C] /usr/local/go/src/runtime/panic.go:42
2016/08/22 15:07:23 [router.go:903] [C] /usr/local/go/src/runtime/sigpanic_unix.go:24
2016/08/22 15:07:23 [router.go:903] [C] /root/dev/go/src/github.com/astaxie/beego/orm/db_utils.go:148
2016/08/22 15:07:23 [router.go:903] [C] /root/dev/go/src/github.com/astaxie/beego/orm/orm_raw.go:571
2016/08/22 15:07:23 [router.go:903] [C] /root/dev/go/src/github.com/astaxie/beego/orm/orm_raw.go:792

**Comment by tangshancheng** [comment]
`} else if fi.fieldType == TypeDateTimeField {`
here missed "fi != nil", 

and this only happens when 
1. you are using raw sql query 
2. colume type is: datetime
3. value you passed in is of type time.Time


To workaround this issue:
In you code, pass in the value for that datatime column as a **string**

E.G.
`orm.Raw("update user set modified_date = ?", time.Now()).Exec()`

change it to 
`orm.Raw("update user set modified_date = ?", time.Now().Format("2006-01-02 15:04:05")).Exec()`

**Comment by astaxie** [comment]
fixed in develop branch
