### ISSUE TITLE
beego 1.12.0.   old process didn't exist when graceful restart?

### ISSUE THREAD

**Issue by nFox18** [astaxie/beego#3717]
beego 1.12.0  centos 

old process didn't  exist when graceful restart.  

app.go   line 161.  
				if err := server.ListenAndServe(); err != nil {
					logs.Critical("ListenAndServe: ", err, fmt.Sprintf("%d", os.Getpid()))
					time.Sleep(100 * time.Microsecond)
					endRunning <- true
				}

endRunning not true when server.ListenAndServe return no error.  
so App.Run won't return.    and process won't exit.

**Comment by nuczzz** [comment]
hi, @nFox18 :
sorry to reply you so late because my PC is broken... the reason of your issue is beego graceful update with [http.Shutdown](https://github.com/astaxie/beego/blob/develop/grace/server.go#L292) in my [pr](https://github.com/astaxie/beego/pull/3494)。In the pr, I filtered out the [http.ErrServerClosed error](https://github.com/astaxie/beego/blob/develop/grace/server.go#L42) because when Shutdown is called, Serve, ListenAndServe, and ListenAndServeTLS immediately return ErrServerClosed. 
After received ErrServerClosed error and wait for read data from [terminalChan](https://github.com/astaxie/beego/blob/develop/grace/server.go#L49), return ErrServerClosed should 
be able to solve the problem. I will test and submit a new pr as soon.
