### ISSUE TITLE
Two beego instances conflict

### ISSUE THREAD

**Issue by paxoscn** [astaxie/beego#3828]
beego 1.11.0
go 1.12.5

I deployed a beego web server on a node and everything worked fine. But when I deployed another beego project onto the same node I could not start the process and received error message as below:

flag redefined: graceful

I tried to modify source code of beego and commented out these two lines in grace.go to fit the error:

`flag.BoolVar(&isChild, "graceful", false, "listen on open fd (after forking)")
flag.StringVar(&socketOrder, "socketorder", "", "previous initialization order - used when more than one listener was started")`

Then I was able to start the process but would there be any further side effects?

**Comment by IamCathal** [comment]
The grace folder is meant to enable hot reloading of beego applications gracefully. I've never used or worked on a similar feature but the blog linked does a good job of explaining the features and difficulties surrounding it. 
http://grisha.org/blog/2014/06/03/graceful-restart-in-golang/

I have been able to run two beego servers simultaneously without any difficulty so I can't reproduce the error. Since the grace package is used to handle reloading of a beego server I think there must be a bug which makes the app think that the other instance is a child instance or something of itself which shouldn't occur outside of when a reload is triggered (which in your case isn't happening it's just running normally).

I think that in your case commenting the two lines out shouldn't effect you unless you get into hot reloading which I'm not sure what triggers that but for the time being it should work. If a hot reload happens under the hood then you might be in trouble

**Comment by zplzpl** [comment]
遇到同样的问题，排除了astaxie/beego 和 beego/beego混用。一个graceful也能出这么多问题？

**Comment by zplzpl** [comment]
version: 1.9.2
