### ISSUE TITLE
 Tag set default value, DB does not display the default value?

### ISSUE THREAD

**Issue by fishyww** [astaxie/beego#4087]
code：
package main

import (
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type User struct {
	Id     int
	Name   string
	Status int `orm:"default(1)"`
}

func init() {
	orm.RegisterDataBase("default", "mysql", "roxxot:xx@tcp(xxx:3306)/xxx?charset=utf8")
	orm.RegisterDriver("mysql", orm.DRMySQL)
	orm.RegisterModel(new(User))
	orm.RunSyncdb("default", false, true)
}

func main() {
	orm.Debug = true
	o := orm.NewOrm()
	user := &User{
		Name: "aa",
	}
	o.Insert(user)
DB：
![image](https://user-images.githubusercontent.com/51019225/88144678-e6704980-cc2b-11ea-8c02-bd270a430ba1.png)

**Comment by flycash** [comment]
Actually the default value is invalid for basic type. In this case, when we decide to generate SQL to insert into DB, we know status = 0, but we don't know the actual value is 0 or you don't set the value.

In other languages, for example, Java, we use boxed type `Integer` rather than `int`. So when `status == null ` we think you don't set the value. 

But golang doesn't have similar structure. We are thinking about refactoring this feature.

**Comment by flycash** [comment]
Please follow #4090, I closed all similar issue.
